spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:15434/users
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8083
  error:
    include-message: always
jwt:
  secret: 3f4b2a7e8f1c3d2a0b5e6c8f2087a4d9c6e5f0bcb16a14f22986f4084e6c6a2d
  duration: 2h