spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:15433/order_service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
  error:
    include-message: always
  servlet:
    context-path: /api/v1
client:
  inventory-service:
    url: http://localhost:8080