spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:15432/inventory_service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
  error:
    include-message: always
springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui
  api-docs:
    path: /api/v1/api-docs